FROM openjdk:11
MAINTAINER Digirise.com
ARG JAR_FILE=target/device-gateway-*.jar
COPY ${JAR_FILE} device-gateway.jar
ENV spring.config.location classpath:application.properties,/opt/gateway.properties
ENTRYPOINT ["java","-jar","/device-gateway.jar"]
EXPOSE 9082