FROM openjdk:11
MAINTAINER Digirise.com
ARG JAR_FILE=target/sai-data-processing-*.jar
COPY ${JAR_FILE} sai-data-processing-server.jar
ENTRYPOINT ["java","-jar","/sai-data-processing-server.jar"]
EXPOSE 9082